name: Auto update

env:
  BUILDER_TOOLS_URL: https://github.com/flatpak/flatpak-builder-tools.git
  BUILDER_TOOLS_BRANCH: master

on:
  schedule:
    - cron: '45 6 * * *'
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - name: Install dependencies
        run: |
          sudo dnf -y install jq python3-pip
          python3 -m pip install requirements-parser
      - uses: actions/checkout@v2
      - name: test git
        run: |
          git status
